language: node_js
node_js:
  - 'lts/carbon'
script:
  - npm run prod
deploy:
  provider: firebase
  token:
    secure: yYZjtke+SYv3D/8L+paIbIKelcevZcN2HB+pnPE1jcS6wyU3yM20Yfn90v69hvE8NuqFFkhO79sJkHXLHw6OlBnZITHHvUv7n6a59OgcqwYFVUNKeO500PLB3ZESP4fAVQT0EvMiM/6a/fUawQaVI2hc2wNwRIPWyBCy4Sj1gXy5zauApDedrVvnHHsbCreBHGWM4Yh4ouiL756XJiooTpIB7T4yz78XMQxalkUs5izsx46scHkyhrS6mZaTwTa4WZZeZj8F0BswxVEVBqL0vC5MEoOpN9Mv+v37e6bC3LMpEADfUjxdU2XiUs5dizQ7Q/gRMbSstnhvWYuP4MqS+xCziBSD+HPW9mMqJhprhS1CZ3Ho5uw6fQ4LxXI/r4UowLqxsHCKwJ+1QVg8N1kA/dEfTrFcFgs/DeYjMm5cZE5hinzFlMSMY9N6uQrqW2UkhX0utwOPP52cf5HXQTtZakHoEiADuqdR3/HLZecErlludOJwAwmTwKP9OXkaXoh4FMCjwp++vmVwyGD6E4icVNd9GjBE6iOkHYuR22hwKkUyPdlhC6fzt790cbCYDxI1jirECVt9WEcKEmE49rN840cYiEkO1me2DKXlrGXMoyAq/swqkLpUAwz/eTPQPU4c8FbnHo1GJLl65IxWN140Q7csH1IUivrrfruL0HCS3nY=
